CREATE TABLE FU_PACK (
FU_PACK_ID	NUMBER		NOT NULL,
SHORT_NAME	VARCHAR2(5) NOT NULL,
LONG_NAME	VARCHAR2(30)	NOT NULL,
APPL_METHOD	VARCHAR2(1)		NOT NULL,
APPL_PERIOD_TYPE	VARCHAR2(1)		DEFAULT 'M' NOT NULL ,
APPL_PERIOD_LENGTH	NUMBER,
SALES_PROMOTION_PERIOD_TO	DATE,
SALES_PROMOTION_PERIOD_FROM	DATE NOT NULL,
RATING_METHOD	VARCHAR2(1)		 NOT NULL,
COMBINE_FU_ACCOUNT	VARCHAR2(1)	,
ASSIGNMENT_LEVEL	VARCHAR2(1)	NOT NULL,
INITIAL_CREDIT	VARCHAR2(1)	,
SETTLEMENT_METHOD	VARCHAR2(1) NOT NULL,
CARRY_OVER_TYPE	VARCHAR2(1)	,
LATE_CALL_ACCEPTANCE	NUMBER	NOT NULL,
CARRY_OVER_LENGTH	NUMBER	,
REC_VERSION	NUMBER		DEFAULT 0 NOT NULL ,
PROCESS_ORDER	NUMBER	DEFAULT	0
)
/


CREATE TABLE BGH_USAGE_GROUPING_1 (
ID	NUMBER	NOT NULL,
NAME	VARCHAR2(50)	NOT NULL,
GROUP_IND	VARCHAR2(1)	NOT NULL,
ROAMING_IND	VARCHAR2(1)	,
SECTION_INDICATOR	VARCHAR2(1)	,
ORDER_INDICATOR	NUMBER	NOT NULL
)
/

CREATE TABLE BGH_USAGE_GROUPING_2 (
ID	NUMBER	NOT NULL,
SUB_ID	NUMBER	NOT NULL,
MICROCELL	VARCHAR2(5)	,
SERVICE	VARCHAR2(5)	,
NETWORK_IND	VARCHAR2(1)	,
TYPE_IND	VARCHAR2(1)	,
TZCODE	VARCHAR2(5)	,
CSP_ID	VARCHAR2(5)	,
LZCODE	NUMBER	,
FU_PACK_ID	NUMBER
)
/
