/* create table dw_promo_mc and DW_PROMO_SN */

create table DWPROMO_MC (
    COD_PROMOCAO_OLTP NUMBER(19) NOT NULL,
    QTD_AMIGOS NUMBER(19),
    DAT_INICIO_CADASTRO_AMIGO DATE,
    DAT_FIM_CADASTRO_AMIGO DATE,
    QTD_PERIODO_VALIDO_AMIGO NUMBER(19),
    COD_UNIDADE_VALIDADE_AMIGO VARCHAR2(10),
    COD_SERVICO_OLTP NUMBER(19),
    DAT_REFERENCIA DATE,
    SHDES VARCHAR2(10)
)
/
create table DWPROMO_SN (
    COD_PROMOCAO_OLTP NUMBER(19) NOT NULL,
    COD_SERVICO_OLTP NUMBER(19),
    DAT_INICIO_SERVICO DATE,
    DAT_FIM_SERVICO DATE,
    DAT_REFERENCIA DATE
)

/* select in contr_services */

SELECT A.SNCODE, A.CO_ID, A.CS_STAT_CHNG
FROM CONTR_SERVICES A
WHERE A.CO_ID = ?
AND A.TMCODE = ?
AND A.SNCODE = ?
AND CS_SEQNO = ( SELECT MAX(C.CS_SEQNO) FROM CONTR_SERVICES C
WHERE C.TMCODE = A.TMCODE
AND C.CO_ID = A.CO_ID
AND C.SNCODE = A.SNCODE )

/* inserts into promotion_exclusivity */

insert into PROMOTION_EXCLUSIVITY values (1, 'P1', 'Promoção 1');
insert into PROMOTION_EXCLUSIVITY values (2, 'P2', 'Promoção 2');
insert into PROMOTION_EXCLUSIVITY values (3, 'P3', 'Promoção 3');
insert into PROMOTION_EXCLUSIVITY values (4, 'P4', 'Promoção 4');
insert into PROMOTION_EXCLUSIVITY values (5, 'P5', 'Promoção 5');
insert into PROMOTION_EXCLUSIVITY values (6, 'P6', 'Promoção 6');
insert into PROMOTION_EXCLUSIVITY values (7, 'P7', 'Promoção 7');
insert into PROMOTION_EXCLUSIVITY values (8, 'NAT06', 'Natal 2006');
insert into PROMOTION_EXCLUSIVITY values (9, 'PTP07', 'PTP 2007');
insert into PROMOTION_EXCLUSIVITY values (10, 'PLD07', 'PLD 2007');
insert into PROMOTION_EXCLUSIVITY values (11, 'MAE07', 'MAE07 2007');
insert into PROMOTION_EXCLUSIVITY values (12, 'M07CI', 'M07CI 2007');
insert into PROMOTION_EXCLUSIVITY values (13, 'PTZB', 'PTZB 2007');
insert into promotion_exclusivity values (14, 'PESST', 'PESST');
insert into promotion_exclusivity values (15, 'PESPR', 'PESPR');


/* inserts into promotion_exclusivity_rel */

insert into PROMOTION_EXCLUSIVITY_REL values (1,2);
insert into PROMOTION_EXCLUSIVITY_REL values (3,1);
insert into PROMOTION_EXCLUSIVITY_REL values (1,4);
insert into PROMOTION_EXCLUSIVITY_REL values (2,4);
insert into PROMOTION_EXCLUSIVITY_REL values (2,5);
insert into PROMOTION_EXCLUSIVITY_REL values (2,6);
insert into PROMOTION_EXCLUSIVITY_REL values (6,2);
insert into PROMOTION_EXCLUSIVITY_REL values (6,3);
insert into PROMOTION_EXCLUSIVITY_REL values (6,8);
insert into PROMOTION_EXCLUSIVITY_REL values (9,8);
insert into PROMOTION_EXCLUSIVITY_REL values (8,10);
insert into PROMOTION_EXCLUSIVITY_REL values (10,9);
insert into PROMOTION_EXCLUSIVITY_REL values (11,12);
insert into PROMOTION_EXCLUSIVITY_REL values (11,2);
insert into PROMOTION_EXCLUSIVITY_REL values (12,1);
insert into PROMOTION_EXCLUSIVITY_REL values (12,3);
insert into PROMOTION_EXCLUSIVITY_REL values (13,12);
insert into promotion_exclusivity_rel values (14, 15);

/* insert into contr_services */

insert into contr_services values(8343005,339,1,509,1,NULL,'080420a','',null,79017916,3,'',0,'',NULL
,'',0,'','',0,NULL,'',NULL,NULL,NULL,to_date('2003-10-11 14:46:10', 'YYYY-MM-DD HH24:MI:SS'),'','','','',NULL,43,NULL,16,'',-206,'DS010RRM','C','',NULL,'',NULL);
insert into contr_services values(8343005,339,1,566,1,NULL,'080422a080520d','',null,79017916,3,'',0,'',NULL
,'',0,'','',0,NULL,'',NULL,NULL,NULL,to_date('2003-10-11 14:46:10', 'YYYY-MM-DD HH24:MI:SS'),'','','','',NULL,43,NULL,16,'',-206,'DS010RRM','C','',NULL,'',NULL);
insert into contr_services values(8343005,339,1,536,1,NULL,'080423a080521d','',null,79017916,3,'',0,'',NULL
,'',0,'','',0,NULL,'',NULL,NULL,NULL,to_date('2003-10-11 14:46:10', 'YYYY-MM-DD HH24:MI:SS'),'','','','',NULL,43,NULL,16,'',-206,'DS010RRM','C','',NULL,'',NULL);
insert into contr_services values(8343005,339,1,537,1,NULL,'080424a080522d','',null,79017916,3,'',0,'',NULL
,'',0,'','',0,NULL,'',NULL,NULL,NULL,to_date('2003-10-11 14:46:10', 'YYYY-MM-DD HH24:MI:SS'),'','','','',NULL,43,NULL,16,'',-206,'DS010RRM','C','',NULL,'',NULL);
insert into contr_services values(8343005,339,1,567,1,NULL,'080622a080720d','',null,79017916,3,'',0,'',NULL
,'',0,'','',0,NULL,'',NULL,NULL,NULL,to_date('2003-10-11 14:46:10', 'YYYY-MM-DD HH24:MI:SS'),'','','','',NULL,43,NULL,16,'',-206,'DS010RRM','C','',NULL,'',NULL);
insert into contr_services values(8343005,339,1,448,1,NULL,'080424a','',null,79017916,3,'',0,'',NULL
,'',0,'','',0,NULL,'',NULL,NULL,NULL,to_date('2003-10-11 14:46:10', 'YYYY-MM-DD HH24:MI:SS'),'','','','',NULL,43,NULL,16,'',-206,'DS010RRM','C','',NULL,'',NULL);


INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,3	,773	,1, null, '090216a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,2, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,3	,772	,1, null, '090215a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,2, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,3	,716	,1, null, '090202a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,2, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,1	,3		,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,2	,5		,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,1	,2		,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,1	,4		,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,1	,1		,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,3	,204	,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,1	,22		,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,12	,207	,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,3	,53		,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,4, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,12	,153	,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,4, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,12	,209	,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,3	,6		,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,3	,13		,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,12	,156	,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,4, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,3	,7		,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,12	,157	,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,12	,208	,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,3	,8		,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,12	,671	,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,3	,14		,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,10	,62		,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,14	,202	,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,3, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,3	,76		,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,4, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,3	,9		,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,4, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,12	,152	,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,4, null,-307,'SYSADM','C',null,null,null,null);
INSERT INTO CONTR_SERVICES VALUES (52146310	,408	,3	,715	,1, null, '090201a', null, to_date('1/3/2009','DD/MM/YYYY'),null,null,null,0,null,null,null,null,null,null,0,null,null,null,null,null,sysdate,null,null,null,null,null,43,null,2, null,-307,'SYSADM','C',null,null,null,null);


/* inserts into dw_promo_mc */

INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00043',1,null,null,NULL,'I',NULL,null,'BIL01')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00044',1,null,null,NULL,'I',NULL,null,'BISML')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00003',1,null,null,NULL,'I',NULL,null,'TTN')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00004',1,null,null,NULL,'I',NULL,null,'MVT')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00006',1,null,null,NULL,'I',NULL,null,'TCT')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00008',9,null,null,NULL,'I',NULL,null,'XMAS2')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00008',3,null,null,NULL,'I',NULL,null,'XMASF')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00009',1,null,null,NULL,'I',NULL,null,'XMAS1')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00011',3,null,null,NULL,NULL,448,null,'PTZB')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00011',3,null,null,NULL,NULL,449,null,'PTZN')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00020',1,null,null,NULL,'I',NULL,null,'LD41')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00020',1,null,null,NULL,'I',NULL,null,'LD41F')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00021',0,null,null,3,'M',NULL,null,'BV41')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00024',0,null,null,NULL,'I',700,null,'NAT06')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00024',0,null,null,NULL,'I',508,null,'NAT06')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00024',0,null,null,NULL,'I',420,null,'NAT06')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00032',0,null,null,NULL,'I',537,null,'MAE07')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00032',0,null,null,NULL,'I',537,null,'M07CI')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00041',0,NULL,NULL,NULL,'I',566,NULL,'PLD07')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00041',0,NULL,NULL,NULL,'I',566,NULL,'PTP07')
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00041',0,NULL,NULL,NULL,'I',567,NULL,'PLD07')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00041',0,NULL,NULL,NULL,'I',567,NULL,'PTP07')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00032',0,null,null,NULL,'I',536,null,'MAE07')
/
INSERT INTO DWPROMO_MC
(COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES
('00032',0,null,null,NULL,'I',536,null,'M07CI')
/

INSERT INTO DWPROMO_MC (COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES ('00716',0,null,null,NULL,'I',716,null,'PESPR')
/

INSERT INTO DWPROMO_MC (COD_PROMOCAO_OLTP,QTD_AMIGOS,DAT_INICIO_CADASTRO_AMIGO,DAT_FIM_CADASTRO_AMIGO,QTD_PERIODO_VALIDO_AMIGO,COD_UNIDADE_VALIDADE_AMIGO,COD_SERVICO_OLTP,DAT_REFERENCIA,SHDES)
VALUES ('00715',0,null,null,NULL,'I',715,null,'PESST')
/



/* insert into DWPROMO_SN */

INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00001','246',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00002','247',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00002','417',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00002','420',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00002','443',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00002','444',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00003','89',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00004','93',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00005','247',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00006','93',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00007','247',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00007','437',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00007','438',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00008','190',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00009','189',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00010','434',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00036','435',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00011','448',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00011','449',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00012','450',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00012','451',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00013','247',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00014','247',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00014','437',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00014','438',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00015','474',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00015','495',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00022','490',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00023','491',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00023','492',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00024','420',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00024','508',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00024','509',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00017','360',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00018','361',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00019','496',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00019','497',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00019','498',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00034','538',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00020','314',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00020','416',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00021','500',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00016','309',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00016','488',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00022','489',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00025','515',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00025','516',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00026','518',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00026','519',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00027','517',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00027','520',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00028','246',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00029','511',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00029','512',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00030','247',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00031','247',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00030','527',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00030','528',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00032','536',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00032','537',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00032','420',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00033','500',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00035','539',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00035','540',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00035','541',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00037','553',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00037','554',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00038','550',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00038','551',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00038','552',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00039','513',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00039','514',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00039','549',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00040','546',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00040','547',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00040','548',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00041','566',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00041','567',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00042','420',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00042','568',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00042','569',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00042','570',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00042','571',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00043','393',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00044','393',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00045','78',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00046','572',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00046','573',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00047','574',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00047','575',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00048','420',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00048','568',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00048','569',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00048','570',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00048','571',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00049','605',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00049','606',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00050','603',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00050','604',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00051','619',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00051','620',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00051','621',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00051','622',null,null,null)
/
INSERT INTO DWPROMO_SN
(COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES
('00019',NULL,null,null,null)



INSERT INTO DWPROMO_SN (COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES ('00716','716',null,null,null)
/
INSERT INTO DWPROMO_SN (COD_PROMOCAO_OLTP,COD_SERVICO_OLTP,DAT_INICIO_SERVICO,DAT_FIM_SERVICO,DAT_REFERENCIA)
VALUES ('00715','715',null,null,null)


