-----------------------------------------------Melhorias03-Abril-2010-------------------------------------

--Esta sera removida posteriormente. Atentar para sua execucao indevidamente.
--DROP TABLE QLF_USAGE_RATES;

-- CREATE TABLES SECTION

CREATE TABLE USAGE_RATES (
	TARIFF_ZONE_UID NUMBER(19,0) CONSTRAINT SYS_C004770 NOT NULL ,
	PLANS_UID NUMBER(19,0) CONSTRAINT SYS_C004771 NOT NULL ,
	SERVICES_UID NUMBER(19,0) CONSTRAINT SYS_C004772 NOT NULL ,
	RATE_TIME_ZONE_UID NUMBER(19,0) CONSTRAINT SYS_C004774 NOT NULL ,
	EFFECTIVE_DATE DATE CONSTRAINT SYS_C004775 NOT NULL ,
	INCOMING_FLAG CHAR (1) DEFAULT 'N' NOT NULL ,
	INIT_VOLUME NUMBER(16,4) NOT NULL ,
	END_VOLUME NUMBER(16,4) NOT NULL ,
	STEP_VOLUME NUMBER(16,4) NOT NULL ,
	STEP_COST NUMBER(16,4) NOT NULL ,
	LOADED_DATE DATE NOT NULL ,
	CUSTOM_1 VARCHAR2 (30),
	CUSTOM_2 VARCHAR2 (30),
	CUSTOM_3 VARCHAR2 (30),
 CONSTRAINT USAGE_RATES_PK PRIMARY KEY (TARIFF_ZONE_UID,PLANS_UID,SERVICES_UID,RATE_TIME_ZONE_UID,EFFECTIVE_DATE,INCOMING_FLAG,INIT_VOLUME) 
) 
/

-- CREATE INDEXES SECTION

CREATE INDEX USAGE_RATES_IDX1 ON USAGE_RATES (TARIFF_ZONE_UID,PLANS_UID,SERVICES_UID,RATE_TIME_ZONE_UID,INCOMING_FLAG) 
/
CREATE INDEX USAGE_RATES_IDX2 ON USAGE_RATES (LOADED_DATE) 
/

-- CREATE FOREIGN KEYS SECTION
ALTER TABLE USAGE_RATES ADD CONSTRAINT USAGE_RATES_FK1 FOREIGN KEY (TARIFF_ZONE_UID) REFERENCES QLF_TARIFF_ZONE (OBJID) 
/
ALTER TABLE USAGE_RATES ADD CONSTRAINT USAGE_RATES_FK2 FOREIGN KEY (PLANS_UID) REFERENCES QLF_PLANS (OBJID) 
/
ALTER TABLE USAGE_RATES ADD CONSTRAINT USAGE_RATES_FK3 FOREIGN KEY (SERVICES_UID) REFERENCES QLF_SERVICES (OBJID) 
/
ALTER TABLE USAGE_RATES ADD CONSTRAINT USAGE_RATES_FK5 FOREIGN KEY (RATE_TIME_ZONE_UID) REFERENCES QLF_RATE_TIME_ZONE (OBJID) 
/

-- CREATE ATTRIBUTE COMMENTS SECTION

COMMENT ON COLUMN USAGE_RATES.EFFECTIVE_DATE IS 'DATA A PARTIR DA QUAL ESTA TARIFA É VÁLIDA. ELA DEIXA DE SER VÁLIDA ASSIM QUE UMA NOVA TARIFA, COM DATA SUPERIOR, FOR INCLUÍDA NA TABELA.'
/
COMMENT ON COLUMN USAGE_RATES.INCOMING_FLAG IS 'INIDICA SE A TARIFA É APLICADA PARA CHAMADAS ORIGINADAS OU RECEBIDAS (A COBRAR, POR EXEMPLO).'
/
COMMENT ON COLUMN USAGE_RATES.INIT_VOLUME IS 'O VOLUME INICIAL A PARTIR DO QUAL ESTA TARIFA É VÁLIDA. GERALMENTE ESTE VALOR É ZERO, INDICANDO QUE É O "PRIMEIRO VALOR" DE TARIFA.
EM CONJUNTO COM O ATRIBUTO END_VOLUME E STEP_VOLUME, ELES PERMITEM A CONFIGURAÇÃO DE VALORES PARA BLOCOS DE N UNIDADES, E VARIANDO EM INTERVALOS (O INIT_VOLUME E END_VOLUME)'
/
COMMENT ON COLUMN USAGE_RATES.END_VOLUME IS 'O VOLUME FINAL ATÉ AONDE ESTA TARIFA É VÁLIDA. GERALMENTE ESTE VALOR É 999, INDICANDO QUE A TARIFA DEVE SER USADA INDEFINIDAMENTE.
EM CONJUNTO COM O ATRIBUTO INIT_VOLUME E STEP_VOLUME, ELES PERMITEM A CONFIGURAÇÃO DE VALORES PARA BLOCOS DE N UNIDADES, E VARIANDO EM INTERVALOS (O INIT_VOLUME E END_VOLUME)'
/
COMMENT ON COLUMN USAGE_RATES.STEP_VOLUME IS 'DE QUANTAS EM QUANTAS UNIDADES DE INIT/END_VOLUME A TARIFA É APLICADA.'
/
COMMENT ON COLUMN USAGE_RATES.STEP_COST IS 'O VALOR DESTE EVENTO DE USO, PARA CADA STEP_VOLUME CONSUMOS, ENQUANTO O VOLUME UTILIZADO ESTIVER DENTRO DA FAIXA CONFIGURADA DE INIT_VOLUME A END_VOLUME.'
/

COMMIT;