
/* adding column */
alter table BILLCHKDB.PROG_DISCOUNT_DESC add STATE VARCHAR2(2);

/* drop old index */
drop index BILLCHKDB.PROG_DISCOUNT_DESC_IDX1;

/* create a new one (DISC_DESCRIPTION + STATE) */
CREATE UNIQUE INDEX BILLCHKDB.PROG_DISCOUNT_DESC_IDX1 ON BILLCHKDB.PROG_DISCOUNT_DESC (DISC_DESCRIPTION, STATE);