CREATE TABLE BILLCHKDB.BCK_PROCESS_CHECKPOINT (
	TRANSACTION_ID			VARCHAR2(19)	NOT NULL,
	REQUEST_KEY					VARCHAR2(128)	NOT NULL,
	REQUEST_STATUS			CHAR(1)				NOT NULL
)
/

CREATE INDEX BILLCHKDB.BCK_CONSEQUENCE_IDX3 ON BCK_CONSEQUENCE (RULE_UID, TRANSACTION_ID)
TABLESPACE INDEXES
/