CREATE TABLE DISC_INTL_ROAMING_AGREE ( 
    COUNTRY_NAME 				VARCHAR2(64) 		NOT NULL
)
/

ALTER TABLE DISC_INTL_ROAMING_AGREE ADD CONSTRAINT DISC_INTL_ROAMING_AGREE_PK PRIMARY KEY (COUNTRY_NAME)
/

CREATE TABLE CONTRACT_PROMOTIONS (
	CONTRACT_NUMBER 			VARCHAR2(30) 		NOT NULL ,
	PROMOTION_CODE 				VARCHAR2(30) 		NOT NULL ,
	ACTIVATION_DATE 			DATE						NOT NULL ,
	EXPIRATION_DATE 			DATE						NOT NULL ,
	PROMOTION_DESC 				VARCHAR2 (64)
) 
/

ALTER TABLE CONTRACT_PROMOTIONS ADD CONSTRAINT CONTRACT_PROMOTIONS_PK PRIMARY KEY (CONTRACT_NUMBER, PROMOTION_CODE)
/

CREATE TABLE QLF_PACKAGE (
	OBJID 							NUMBER(19,0) NOT NULL ,
	SHORT_DESC 					VARCHAR2(16) NOT NULL ,
	DESCRIPTION 				VARCHAR2(64) NOT NULL ,
	CUSTOM_1 						VARCHAR2(30),
	CUSTOM_2 						VARCHAR2(30),
	CUSTOM_3 						VARCHAR2(30)
) 
/

ALTER TABLE QLF_PACKAGE ADD CONSTRAINT QLF_PACKAGE_PK PRIMARY KEY (OBJID)
/

CREATE UNIQUE INDEX QLF_PACKAGES_IDX1 ON QLF_PACKAGE (SHORT_DESC) 
/


CREATE TABLE QLF_PLANS_PACKAGES (
	PLAN_UID 						NUMBER(19,0) NOT NULL ,
	PACKAGE_UID 				NUMBER(19,0) NOT NULL
) 
/

ALTER TABLE QLF_PLANS_PACKAGES ADD CONSTRAINT QLF_PLANS_PACKAGES_PK PRIMARY KEY (PLAN_UID, PACKAGE_UID)
/

ALTER TABLE QLF_PLANS_PACKAGES ADD CONSTRAINT QLF_PLANS_PACKAGES_FK1 
		FOREIGN KEY (PLAN_UID) REFERENCES QLF_PLANS (OBJID) ON DELETE CASCADE
/

ALTER TABLE QLF_PLANS_PACKAGES ADD CONSTRAINT QLF_PLANS_PACKAGES_FK2 
		FOREIGN KEY (PACKAGE_UID) REFERENCES QLF_PACKAGE (OBJID) ON DELETE CASCADE
/


ALTER TABLE QLF_PLANS ADD PACK_MANDATORY CHAR(1)  DEFAULT 'F' NOT NULL
/

Create table QLF_USAGE_GROUP_LD (
	OBJID Number(19,0) NOT NULL ,
	NAME Varchar2 (50) NOT NULL ,
	CSP_ID Varchar2 (2),
	CUSTOM_1 Varchar2 (30),
	CUSTOM_2 Varchar2 (30),
	CUSTOM_3 Varchar2 (30)
) 
/

ALTER TABLE QLF_USAGE_GROUP_LD ADD CONSTRAINT QLF_USAGE_GROUP_LD_PK PRIMARY KEY (OBJID)
/

Create UNIQUE Index QLF_USAGE_GROUP_LD_IDX1 ON QLF_USAGE_GROUP_LD (NAME) 
/


/***************

CREATE TABLE MPUFFTAB (
    FFCODE NUMBER NOT NULL,
    CO_ID NUMBER NOT NULL,
    DES VARCHAR2(20) ,
    SHDES VARCHAR2(5) ,
    SCALEFACTOR NUMBER(16,8) ,
    UNSPECIFIC_ORIGIN VARCHAR2(1) ,
    CLOSURE VARCHAR2(1) NOT NULL,
    REC_VERSION NUMBER NOT NULL,
    RESET_FLAG CHAR(1) ,
    USER_LIMIT NUMBER ,
    USED_COUNTER NUMBER ,
    LIMITED_FLAG CHAR(1) ,
    PRIORITY NUMBER(38) ,
    SNCODE VARCHAR2(50) ,
    ZNCODE VARCHAR2(50) ,
    TTCODE VARCHAR2(50) ,
    LZCODE VARCHAR2(50) ,
    SPCODE VARCHAR2(50) ,
    TDCODE VARCHAR2(50) ,
    UMCODE NUMBER(38) ,
    FREEUNITS_IND CHAR(1) ,
    PRICEPLAN_IND CHAR(1) ,
    PRICEMECH_TYPE CHAR(1) ,
    PRICE_VALUE NUMBER(16,8)  
)
/

CREATE TABLE CONTR_SERVICES (
    CO_ID NUMBER NOT NULL,  
    TMCODE NUMBER NOT NULL,  
    SPCODE NUMBER NOT NULL, 
    SNCODE NUMBER NOT NULL,  
    CS_SEQNO NUMBER NOT NULL,
    CS_CHANNEL_NUM NUMBER,
    CS_STAT_CHNG VARCHAR2(240),
    CS_ON_CBB VARCHAR2(1),
    CS_DATE_BILLED DATE,
    CS_REQUEST NUMBER,
    SN_CLASS NUMBER,
    CS_OVW_SUBSCR VARCHAR2(1),
    CS_SUBSCRIPT NUMBER(16,8),
    CS_OVW_ACCESS VARCHAR2(1),
    CS_OVW_ACC_PRD NUMBER,
    CS_OVW_ACC_FIRST VARCHAR2(1),
    CS_ACCESS NUMBER(16,8),
    CS_PENDING_STATE VARCHAR2(8),
    CS_CHANNEL_EXCL VARCHAR2(1),
    CS_DIS_SUBSCR NUMBER(16,8),
    CS_ADV_CHARGE NUMBER(16,8),
    CS_SRV_TYPE VARCHAR2(1),
    SUBPAYER NUMBER,
    USGPAYER NUMBER,
    ACCPAYER NUMBER,
    CS_ENTDATE VARCHAR2(30),
    CS_OVW_LAST VARCHAR2(1),
    INSTALL_DATE DATE,
    TRIAL_END_DATE DATE,
    CS_ADV_CHARGE_END_DATE DATE,
    PRM_VALUE_ID NUMBER,
    CURRENCY NUMBER NOT NULL,
    CS_ADV_CHARGE_CURRENCY NUMBER,
    REC_VERSION NUMBER NOT NULL,
    SRV_SUBTYPE VARCHAR2(1),
    DEALER_ID NUMBER,
    USERNAME VARCHAR2(100),
    INITIATOR_TYPE CHAR(1) NOT NULL,
    BACKUP_CS_OVW_ACCESS VARCHAR2(1),
    BACKUP_CS_OVW_ACC_PRD NUMBER,
    BACKUP_CS_OVW_ACC_FIRST VARCHAR2(1),
    BACKUP_CS_ACCESS NUMBER(16,8)
)
/

CREATE TABLE MPULKFXO (
    FFCODE NUMBER NOT NULL,
    FF_ELEMENT_SEQNO NUMBER NOT NULL,
    ORIGIN VARCHAR2(63) NOT NULL,
    DESTINATION VARCHAR2(63) NOT NULL,
    DEST_NPCODE NUMBER NOT NULL,
    REC_VERSION NUMBER NOT NULL,
    ORIGIN_NPCODE NUMBER NOT NULL  
)
/

CREATE TABLE MPULKTMB (
    TMCODE NUMBER  NOT NULL,
    VSCODE NUMBER NOT NULL,
    VSDATE DATE  NOT NULL,
    STATUS VARCHAR2(1) NOT NULL,
    SPCODE NUMBER NOT NULL,
    SNCODE NUMBER NOT NULL,
    SUBSCRIPT NUMBER(16,8),
    ACCESSFEE NUMBER(16,8),
    EVENT NUMBER(16,8),
    ECHIND VARCHAR2(1),
    AMTIND VARCHAR2(1),
    FRQIND VARCHAR2(1),
    SRVIND VARCHAR2(1),
    PROIND VARCHAR2(1),
    ADVIND VARCHAR2(1),
    SUSIND VARCHAR2(1),
    LTCODE NUMBER,
    PLCODE NUMBER,
    BILLFREQ NUMBER,
    FREEDAYS NUMBER,
    ACCGLCODE VARCHAR2(30),
    SUBGLCODE VARCHAR2(30),
    USGGLCODE VARCHAR2(30),
    ACCJCID NUMBER,
    USGJCID NUMBER,
    SUBJCID NUMBER,
    CSIND VARCHAR2(1),
    CLCODE NUMBER,
    BILL_FMT VARCHAR2(30),
    PPCODE NUMBER,
    ACCSERV_CATCODE VARCHAR2(10),
    ACCSERV_CODE VARCHAR2(10),
    ACCSERV_TYPE VARCHAR2(3),
    USGSERV_CATCODE VARCHAR2(10),
    USGSERV_CODE VARCHAR2(10),
    USGSERV_TYPE VARCHAR2(3),
    SUBSERV_CATCODE VARCHAR2(10),
    SUBSERV_CODE VARCHAR2(10),
    SUBSERV_TYPE VARCHAR2(3),
    DEPOSIT NUMBER(16,8),
    INTERVAL_TYPE VARCHAR2(1),
    INTERVAL NUMBER,
    SUBGLCODE_DISC VARCHAR2(30),
    ACCGLCODE_DISC VARCHAR2(30),
    USGGLCODE_DISC VARCHAR2(30),
    SUBGLCODE_MINCOM VARCHAR2(30),
    ACCGLCODE_MINCOM VARCHAR2(30),
    USGGLCODE_MINCOM VARCHAR2(30),
    SUBJCID_DISC NUMBER,
    ACCJCID_DISC NUMBER,
    USGJCID_DISC NUMBER,
    SUBJCID_MINCOM NUMBER,
    ACCJCID_MINCOM NUMBER,
    USGJCID_MINCOM NUMBER,
    PV_COMBI_ID NUMBER,
    PRM_PRINT_IND VARCHAR2(1),
    PRINTSUBSCRIND VARCHAR2(1) NOT NULL,
    PRINTACCESSIND VARCHAR2(1) NOT NULL,
    REC_VERSION NUMBER NOT NULL
)
/

CREATE TABLE acc_sgt_rel_customizacoes
    (cliente                        VARCHAR2(30),
    data_ativacao                  DATE,
    valor_desvio_assin_plano       NUMBER(10,4)
)
/

***************/



