ALTER TABLE BCK_CARRIER_DATA ADD LOCAL_FLAG CHAR(1) DEFAULT 'F' NOT NULL
/

DROP INDEX BCK_CARRIER_DATA_IDX1
/

CREATE INDEX BCK_CARRIER_DATA_IDX1 ON  BCK_CARRIER_DATA (CARRIER_DM_UID)
TABLESPACE INDEXES
/