
DROP TABLE BILLCHKDB.PROG_DISCOUNT_PLANS;

 CREATE OR REPLACE FORCE VIEW BCK_CYCLE_DM_VIEW 
	(OBJID, CYCLE_CODE, CUT_DATE, ISSUE_DATE, DUE_DATE) AS 
	( SELECT OBJID, CYCLE_CODE, to_char(CUT_DATE) as CUT_DATE, 
	         to_char(ISSUE_DATE) as ISSUE_DATE, 
	         to_char(DUE_DATE) as DUE_DATE
   from BCK_CYCLE_DM )	         
/

ALTER TABLE BILLCHKDB.PROMOTION_EXCLUSIVITY_REL DROP CONSTRAINT 
PROMOTION_EXCLUSIVITY_REL_FK1
/

ALTER TABLE BILLCHKDB.PROMOTION_EXCLUSIVITY_REL ADD CONSTRAINT 
    PROMOTION_EXCLUSIVITY_REL_FK1 FOREIGN KEY (OBJID_1) 
    REFERENCES BILLCHKDB.PROMOTION_EXCLUSIVITY (OBJID) 
    ON DELETE CASCADE
/


ALTER TABLE BILLCHKDB.PROMOTION_EXCLUSIVITY_REL DROP CONSTRAINT 
PROMOTION_EXCLUSIVITY_REL_FK2
/

ALTER TABLE BILLCHKDB.PROMOTION_EXCLUSIVITY_REL ADD CONSTRAINT 
    PROMOTION_EXCLUSIVITY_REL_FK2 FOREIGN KEY (OBJID_2) 
		REFERENCES BILLCHKDB.PROMOTION_EXCLUSIVITY (OBJID)
    ON DELETE CASCADE
/