--Table: BCK_PARM_NF_THRESHOLD
CREATE TABLE BILLCHKDB.BCK_PARM_NF_THRESHOLD (
	OBJID 	            NUMBER(19,0)	NOT NULL,
	LOCAL_FLAG			CHAR(1)			NOT NULL,
	LOWER_LIMIT			NUMBER(19,4)			,
	UPPER_LIMIT			NUMBER(19,4)			,
	HINT_MESSAGE		VARCHAR2(128)			,
	CUSTOM_1	    	VARCHAR2(30)			,
	CUSTOM_2            VARCHAR2(30)			,
	CUSTOM_3            VARCHAR2(30)
);


ALTER TABLE BILLCHKDB.BCK_PARM_NF_THRESHOLD ADD CONSTRAINT BCK_PARM_NF_THRESHOLD_PK
	PRIMARY KEY(OBJID);

CREATE UNIQUE INDEX BILLCHKDB.BCK_PARM_NF_THRESHOLD_IDX1 ON BILLCHKDB.BCK_PARM_NF_THRESHOLD (LOCAL_FLAG);

