-- permitindo 2 endereços por operadora
ALTER TABLE BILLCHKDB.BCK_CARRIER_DATA ADD LOCAL_FLAG CHAR(1) DEFAULT 'F' NOT NULL
/

DROP INDEX BILLCHKDB.BCK_CARRIER_DATA_IDX1
/

CREATE INDEX BILLCHKDB.BCK_CARRIER_DATA_IDX1 ON  BILLCHKDB.BCK_CARRIER_DATA (CARRIER_DM_UID)
TABLESPACE INDEXES
/

-- adicionando novo campo 
alter table BILLCHKDB.WEB_BUNDLEFILE ADD RECORD_COUNT INTEGER DEFAULT 0
/
