
DROP SEQUENCE BCK_CONSEQUENCE_UID;
DROP TABLE BCK_CONSEQUENCE;
DROP TABLE BCK_CONSEQUENCE_ATTR;
DROP TABLE BCK_RULE;

TRUNCATE TABLE BCK_INVOICE_FACT;
TRUNCATE TABLE BCK_CONTRACT_TOTALS_FACT;

DELETE FROM BCK_GEO_DM;

-- Table: BCK_RULE
CREATE TABLE BCK_RULE (	
	OBJID 				NUMBER(19,0) 	NOT NULL, 
	RULE_CODE 			VARCHAR2(16) 	NOT NULL, 
	RULE_NAME 			VARCHAR2(32) 	NOT NULL, 
	DESCRIPTION 		VARCHAR2(128)			, 
	RULE_TYPE_UID 		NUMBER(19,0)			, 
	CUSTOM_1 			VARCHAR2(30)			, 
	CUSTOM_2 			VARCHAR2(30)			, 
	CUSTOM_3 			VARCHAR2(30)
);

ALTER TABLE BCK_RULE ADD CONSTRAINT BCK_RULE_PK
	 PRIMARY KEY (OBJID);
	 
ALTER TABLE BCK_RULE ADD CONSTRAINT BCK_RULE_UK1
	 UNIQUE (RULE_CODE);

ALTER TABLE BCK_RULE ADD CONSTRAINT BCK_RULE_FK1
	FOREIGN KEY (RULE_TYPE_UID) REFERENCES BCK_RULE_TYPE (OBJID);

-- Table: BCK_CONSEQUENCE_ATTR
CREATE TABLE BCK_CONSEQUENCE_ATTR (
	 OBJID NUMBER(19,0) NOT NULL, 
   ATTR_NAME_1 VARCHAR2(32),
   ATTR_VALUE_1 VARCHAR2(128),
   ATTR_NAME_2 VARCHAR2(32),
   ATTR_VALUE_2 VARCHAR2(128),
   ATTR_NAME_3 VARCHAR2(32),
   ATTR_VALUE_3 VARCHAR2(128),
   ATTR_NAME_4 VARCHAR2(32),
   ATTR_VALUE_4 VARCHAR2(128),
   ATTR_NAME_5 VARCHAR2(32),
   ATTR_VALUE_5 VARCHAR2(128),
   ATTR_NAME_6 VARCHAR2(32),
   ATTR_VALUE_6 VARCHAR2(128),
   ATTR_NAME_7 VARCHAR2(32),
   ATTR_VALUE_7 VARCHAR2(128),
   ATTR_NAME_8 VARCHAR2(32),
   ATTR_VALUE_8 VARCHAR2(128),
   ATTR_NAME_9 VARCHAR2(32),
   ATTR_VALUE_9 VARCHAR2(128),
   ATTR_NAME_10 VARCHAR2(32),
   ATTR_VALUE_10 VARCHAR2(128),
   ATTR_NAME_11 VARCHAR2(32),
   ATTR_VALUE_11 VARCHAR2(128),
   ATTR_NAME_12 VARCHAR2(32),
   ATTR_VALUE_12 VARCHAR2(128),
   ATTR_NAME_13 VARCHAR2(32),
   ATTR_VALUE_13 VARCHAR2(128),
   ATTR_NAME_14 VARCHAR2(32),
   ATTR_VALUE_14 VARCHAR2(128),
   ATTR_NAME_15 VARCHAR2(32),
   ATTR_VALUE_15 VARCHAR2(128),
   ATTR_NAME_16 VARCHAR2(32),
   ATTR_VALUE_16 VARCHAR2(128),
   ATTR_NAME_17 VARCHAR2(32),
   ATTR_VALUE_17 VARCHAR2(128),
   ATTR_NAME_18 VARCHAR2(32),
   ATTR_VALUE_18 VARCHAR2(128),
   ATTR_NAME_19 VARCHAR2(32),
   ATTR_VALUE_19 VARCHAR2(128),
   ATTR_NAME_20 VARCHAR2(32),
   ATTR_VALUE_20 VARCHAR2(128)
);

ALTER TABLE BCK_CONSEQUENCE_ATTR ADD CONSTRAINT BCK_CONSEQUENCE_ATTR_PK
	 PRIMARY KEY (OBJID); 

 
-- Table: BCK_CONSEQUENCE
CREATE TABLE  BCK_CONSEQUENCE (	
 	OBJID 				NUMBER(19,0) 	NOT NULL, 
	ACCOUNT_UID 		NUMBER(19,0) 	NOT NULL,
	CARRIER_UID 		NUMBER(19,0) 	NOT NULL,
	CYCLE_UID 			NUMBER(19,0) 	NOT NULL,
	GEO_UID 			NUMBER(19,0) 	NOT NULL,
	TIME_UID 			NUMBER(19,0) 	NOT NULL,
	RULE_UID 			NUMBER(19,0) 	NOT NULL,
	TRANSACTION_ID 		VARCHAR2(64)			, 
	DESCRIPTION 		VARCHAR2(128)			, 
	CONSEQUENCE_LEVEL 	VARCHAR2(10) 	NOT NULL,
    ATTRIBUTE_UID       NUMBER(19)      NOT NULL,
    FILENAME            VARCHAR2(256)           ,
	CUSTOM_1 			VARCHAR2(30)			, 
	CUSTOM_2 			VARCHAR2(30)			, 
	CUSTOM_3 			VARCHAR2(30)			, 
	CUSTOM_4 			VARCHAR2(30)			, 
	CUSTOM_5 			VARCHAR2(30)
);

ALTER TABLE BCK_CONSEQUENCE ADD CONSTRAINT BCK_CONSEQUENCE_PK
	PRIMARY KEY (OBJID); 
	
ALTER TABLE BCK_CONSEQUENCE ADD CONSTRAINT BCK_CONSEQUENCE_FK1
	 FOREIGN KEY (ACCOUNT_UID) REFERENCES BCK_ACCOUNT_DM (OBJID);
	  
ALTER TABLE BCK_CONSEQUENCE ADD CONSTRAINT BCK_CONSEQUENCE_FK2
	FOREIGN KEY (TIME_UID) REFERENCES BCK_TIME_DM (OBJID);
	
ALTER TABLE BCK_CONSEQUENCE ADD CONSTRAINT BCK_CONSEQUENCE_FK3
	FOREIGN KEY (RULE_UID) REFERENCES BCK_RULE (OBJID);
	
ALTER TABLE BCK_CONSEQUENCE ADD CONSTRAINT BCK_CONSEQUENCE_FK4
	FOREIGN KEY (GEO_UID) REFERENCES BCK_GEO_DM (OBJID);
	
ALTER TABLE BCK_CONSEQUENCE ADD CONSTRAINT BCK_CONSEQUENCE_FK5
	FOREIGN KEY (CARRIER_UID) REFERENCES BCK_CARRIER_DM (OBJID);
	
ALTER TABLE BCK_CONSEQUENCE ADD CONSTRAINT BCK_CONSEQUENCE_FK6
	FOREIGN KEY (CYCLE_UID) REFERENCES BCK_CYCLE_DM (OBJID);

ALTER TABLE BCK_CONSEQUENCE ADD CONSTRAINT BCK_CONSEQUENCE_FK7
  FOREIGN KEY (ATTRIBUTE_UID) REFERENCES BCK_CONSEQUENCE_ATTR (OBJID);
  
  
CREATE UNIQUE INDEX BCK_CONSEQUENCE_IDX1 ON BCK_CONSEQUENCE (ATTRIBUTE_UID);  

CREATE INDEX BCK_CONSEQUENCE_IDX2 ON BCK_CONSEQUENCE (TRANSACTION_ID, RULE_UID);


-- sequences	 
CREATE SEQUENCE BCK_CONSEQUENCE_UID INCREMENT BY 1 START WITH 1;



INSERT INTO BCK_RULE VALUES ( 32, 'R00-1', 'Cenário de Rating Desconhecido', null, 1, null,null,null);
INSERT INTO BCK_RULE VALUES ( 31, 'R01-1', 'Tarifação de Chamada Incorreta', null, 1, null,null,null);
INSERT INTO BCK_RULE VALUES (  1, 'R01-4',  'Uso com Valor Negativo', 							null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES (  2, 'R01-5',  'Limites para Eventos de Uso', 					null, 2, null, null, null );
INSERT INTO BCK_RULE VALUES (  3, 'R01-7',  'Campos Ausentes em Uso', 							null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES (  4, 'R01-8',  'Decurso de Prazo em Uso', 							null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES (  5, 'R01-9',  'Eventos de Uso Duplicados', 						null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES ( 29, 'R01-9A', 'Detalhe de Uso Duplicado', 						null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES (  6, 'R01-13', 'Eventos de Uso Sobrepostos', 					null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES ( 30, 'R01-13A', 'Detalhe de Uso Sobreposto', 					null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES (  7, 'R10-0',  'Validação de Data de Corte', 					null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES (  8, 'R10-1',  'Validação de Data de Emissão', 				null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES (  9, 'R10-2',  'Validação de Mês de Referência', 			null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES ( 10, 'R11-1',  'Validação da Data de Vencimento', 			null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES ( 11, 'R12-1',  'Validação de Totais de Uso', 					null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES ( 12, 'R12-6',  'Validação de Total de NF', 						null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES ( 13, 'R12-4',  'Validação de Total de Contrato', 			null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES ( 14, 'R12-5',  'Validação de Total da Fatura', 				null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES ( 15, 'R12-2',  'Validação de Limites de NF', 					null, 2, null, null, null );
INSERT INTO BCK_RULE VALUES ( 16, 'R14-1',  'Validação de Código de Barras', 				null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES ( 17, 'R14-3',  'Dados da Ficha de Arrecadação', 				null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES ( 18, 'R17-2',  'Batimento de Fatura contra NF', 				null, 1, null, null, null );
INSERT INTO BCK_RULE VALUES ( 19, 'R10-3',  'Formato de Data de Emissão', 					null, 3, null, null, null );
INSERT INTO BCK_RULE VALUES ( 20, 'R11-2',  'Formato de Data de Vencimento', 				null, 3, null, null, null );
INSERT INTO BCK_RULE VALUES ( 44, 'R14-5',  'Dados da Operadora Não Conferem', 		null, 1, null, null, null );
