/* rollback */
update bck_rule set rule_name = 'Chamada na Seção Incorreta' where objid = 23;
update bck_rule set rule_name = 'Pacote Diferente do Plano' where objid = 58;
update bck_rule set rule_name = 'Plano sem Pacote Obrigatório' where objid = 59;
update bck_rule set rule_name = 'Dados da Operadora Não Conferem' where objid = 44;
update bck_rule set rule_name = 'Chamadas Zeradas sem Benefícios' where objid = 49;
update bck_rule set rule_name = 'Detalhe de Uso Sobreposto' where objid = 30;
update bck_rule set rule_name = 'Chamadas Fatiadas' where objid = 38;
update bck_rule set rule_name = 'Uso com Valor Negativo' where objid = 1;
update bck_rule set rule_name = 'Limites para Eventos de Uso' where objid = 2;
update bck_rule set rule_name = 'Duração Inválida para Uso' where objid = 24;
update bck_rule set rule_name = 'Campos Ausentes em Uso' where objid = 3;
update bck_rule set rule_name = 'Decurso de Prazo em Uso' where objid = 4;
update bck_rule set rule_name = 'Detalhe de Uso Duplicado' where objid = 29;
update bck_rule set rule_name = 'Desconto Progressivo' where objid = 65;
update bck_rule set rule_name = 'Serviço Não Cadastrado' where objid = 22;
update bck_rule set rule_name = 'Benefício Inválido' where objid = 50;
update bck_rule set rule_name = 'Validação de Franquias' where objid = 60;
update bck_rule set rule_name = 'Hierarquia de Franquias' where objid = 62;
update bck_rule set rule_name = 'Validação de CredCorp' where objid = 51;
update bck_rule set rule_name = 'Validação de Chamadas em MC' where objid = 52;
update bck_rule set rule_name = 'Uso Duplicado Entre Ciclos' where objid = 46;
update bck_rule set rule_name = 'Plano Não Permite Serviço' where objid = 25;
update bck_rule set rule_name = 'Numeração da NF Incorreta' where objid = 26;
update bck_rule set rule_name = 'Série da NF Incorreta' where objid = 27;
update bck_rule set rule_name = 'Débito Automático Mal Formado' where objid = 47;
update bck_rule set rule_name = 'Formato de Data de Emissão' where objid = 19;
update bck_rule set rule_name = 'Formato de Data de Vencimento' where objid = 20;
update bck_rule set rule_name = 'Validação de Totais de Uso' where objid = 11;
update bck_rule set rule_name = 'Validação de Limites de NF' where objid = 15;
update bck_rule set rule_name = 'Validação de Total de Contrato' where objid = 13;
update bck_rule set rule_name = 'Validação de Total da Fatura' where objid = 14;
update bck_rule set rule_name = 'Validação de Total de NF' where objid = 12;
update bck_rule set rule_name = 'ICMS de Uso Incorreto' where objid = 39;
update bck_rule set rule_name = 'Imposto do Serviço Incorreto' where objid = 40;
update bck_rule set rule_name = 'Validação de ICMS na NF' where objid = 53;
update bck_rule set rule_name = 'Validação de Hashcode' where objid = 37;
update bck_rule set rule_name = 'Batimento de Fatura contra NF' where objid = 18;
update bck_rule set rule_name = 'Valor de Promoções' where objid = 54;
update bck_rule set rule_name = 'Limites de Promoções' where objid = 55;
update bck_rule set rule_name = 'Promoção Fora da Vigência' where objid = 56;
update bck_rule set rule_name = 'Promoções Não Compatíveis' where objid = 64;
update bck_rule set rule_name = 'Cobranças de Fidelização' where objid = 63;
update bck_rule set rule_name = 'Cobrança de Taxa de Adesão' where objid = 57;
update bck_rule set rule_name = 'Limites para OCC' where objid = 43;
update bck_rule set rule_name = 'Duplicidade de OCCs' where objid = 41;
update bck_rule set rule_name = 'Cobrança Indevida de Multa/Juros' where objid = 61;
update bck_rule set rule_name = 'Validação de Data de Corte' where objid = 1001;
update bck_rule set rule_name = 'Validação de Data de Emissão' where objid = 1002;
update bck_rule set rule_name = 'Validação de Mês de Referência' where objid = 1003;
update bck_rule set rule_name = 'Validação da Data de Vencimento' where objid = 1004;
