
ALTER SESSION
SET NLS_DATE_FORMAT='DD/MM/YYYY'
/

INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,3,403,1,NULL,'071024a|080314d',NULL,'25/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'V',NULL,NULL,NULL,'24/10/2007',NULL,NULL,NULL,NULL,68749419,43,NULL,10,'C',-3834,'T3045653','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,1,1,1,NULL,'051022a|080314d',NULL,'25/06/2008',24948874,1,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,36,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,1,2,1,NULL,'051022a|080314d',NULL,'25/06/2008',24948874,2,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,36,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,1,3,1,NULL,'051022a|080314d',NULL,'25/06/2008',24948874,3,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,36,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,1,4,1,NULL,'051022a|080314d',NULL,'25/06/2008',24948874,4,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,36,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,2,5,1,NULL,'051022a|080314d',NULL,'25/06/2008',24948874,5,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,36,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,3,7,1,NULL,'051022a|080314d',NULL,'25/06/2008',24948874,7,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,36,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,3,8,1,NULL,'051022a|080314d',NULL,'25/06/2008',24948874,8,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,36,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,3,9,1,NULL,'051022a|080314d',NULL,'25/06/2008',24948874,9,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,22368364,43,NULL,37,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,3,13,1,NULL,'051022a|080314d',NULL,'25/06/2008',24948874,13,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,36,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,3,14,1,NULL,'051022a|080314d',NULL,'25/06/2008',24948874,14,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,36,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,1,22,1,NULL,'051022a|080314d',NULL,'25/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,36,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,3,53,1,NULL,'051022a|080314d',NULL,'25/06/2008',24948874,53,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,22368365,43,NULL,37,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,10,62,1,NULL,'051022a|080314d',NULL,'25/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,36,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,12,157,1,NULL,'051022a|080314d',NULL,'25/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,36,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,14,202,1,NULL,'051022a|080314d',NULL,'25/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,36,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,12,209,1,NULL,'051022a|080314d',NULL,'25/06/2008',24948874,209,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,36,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,100,3,355,1,NULL,'061230a|080314d',NULL,'25/06/2008',58377115,355,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'30/12/2006',NULL,NULL,NULL,NULL,44645266,43,NULL,21,NULL,-2914,'APPINT','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,3,604,2,NULL,'080315a',NULL,'25/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,'V',NULL,NULL,NULL,'15/03/2008',NULL,NULL,NULL,NULL,76603790,43,NULL,5,'C',-20078,'T3073455','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,1,1,2,NULL,'080314a',NULL,'25/06/2008',24948874,1,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,4,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,1,2,2,NULL,'080314a',NULL,'25/06/2008',24948874,2,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,4,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,1,3,2,NULL,'080314a|080403d|080530a|080717d',NULL,'25/06/2008',120116200,3,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,10,NULL,-20664,'BANDOLI1','D',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,1,4,2,NULL,'080314a|080403d|080530a|080717d',NULL,'25/06/2008',120116200,4,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,10,NULL,-20664,'BANDOLI1','D',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,2,5,2,NULL,'080314a|080403d|080530a|080717d',NULL,'25/06/2008',120116200,5,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,10,NULL,-20664,'BANDOLI1','D',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,3,7,2,NULL,'080314a|080403d|080530a|080717d',NULL,'25/06/2008',120116200,7,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,10,NULL,-20664,'BANDOLI1','D',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,3,8,2,NULL,'080314a|080403d|080530a|080717d',NULL,'25/06/2008',120116200,8,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,10,NULL,-20664,'BANDOLI1','D',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,3,9,2,NULL,'080314a|080403d|080530a|080717d',NULL,'25/06/2008',120116200,9,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,22368364,43,NULL,10,NULL,-20664,'BANDOLI1','D',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,3,13,2,NULL,'080314a|080403d|080530a|080717d',NULL,'25/06/2008',120116200,13,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,10,NULL,-20664,'BANDOLI1','D',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,3,14,2,NULL,'080314a|080403d|080530a|080717d',NULL,'25/06/2008',120116200,14,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,10,NULL,-20664,'BANDOLI1','D',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,1,22,2,NULL,'080314a',NULL,'25/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,4,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,3,53,2,NULL,'080314a|080403d|080530a|080717d',NULL,'25/06/2008',120116200,53,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,22368365,43,NULL,10,NULL,-20664,'BANDOLI1','D',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,10,62,2,NULL,'080314a',NULL,'25/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,4,NULL,-20664,'BANDOLI1','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,12,157,2,NULL,'080314a|080403d|080530a|080717d',NULL,'25/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,7,NULL,-20664,'BANDOLI1','D',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,14,202,2,NULL,'080314a|080403d|080530a|080717d',NULL,'25/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,7,NULL,-20664,'BANDOLI1','D',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,12,209,2,NULL,'080314a|080403d|080530a|080717d',NULL,'25/06/2008',120116200,209,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,10,NULL,-20664,'BANDOLI1','D',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,3,355,2,NULL,'080314a',NULL,'25/06/2008',58377115,355,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'30/12/2006',NULL,NULL,NULL,NULL,44645266,43,NULL,4,NULL,-2914,'APPINT','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,3,403,2,NULL,'080314a',NULL,'25/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'V',NULL,NULL,NULL,'24/10/2007',NULL,NULL,NULL,NULL,68749419,43,NULL,4,'C',-3834,'T3045653','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,3,76,2,NULL,'080314a',NULL,'25/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'V',NULL,NULL,NULL,'14/03/2008',NULL,NULL,NULL,NULL,76586062,43,NULL,4,'C',-37,'F8025809','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618517,303,3,75,2,NULL,'080403a|080530d|080717a',NULL,'25/06/2008',120116203,75,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'3/04/2008',NULL,NULL,NULL,NULL,NULL,43,NULL,8,NULL,NULL,NULL,'D',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,3,355,1,NULL,'071012a',NULL,'25/06/2008',84925360,355,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'12/10/2007',NULL,NULL,NULL,NULL,67791902,43,NULL,11,NULL,-2914,'APPINT','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,3,320,1,NULL,'080307a',NULL,'25/06/2008',NULL,320,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'7/03/2008',NULL,NULL,NULL,NULL,NULL,43,NULL,5,NULL,-307,'APPINT','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,3,54,1,NULL,'070112a',NULL,'25/06/2008',60026718,54,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'12/01/2007',NULL,NULL,NULL,NULL,45561565,43,NULL,20,NULL,-307,'APPINT','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,1,1,1,NULL,'051022a',NULL,'25/06/2008',24948886,1,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-9076,'DAGONL','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,1,2,1,NULL,'051022a',NULL,'25/06/2008',24948886,2,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-9076,'DAGONL','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,1,3,1,NULL,'051022a',NULL,'25/06/2008',24948886,3,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-9076,'DAGONL','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,1,4,1,NULL,'051022a',NULL,'25/06/2008',24948886,4,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-9076,'DAGONL','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,2,5,1,NULL,'051022a',NULL,'25/06/2008',24948886,5,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-9076,'DAGONL','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,3,7,1,NULL,'051022a',NULL,'25/06/2008',24948886,7,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-9076,'DAGONL','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,3,8,1,NULL,'051022a',NULL,'25/06/2008',24948886,8,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-9076,'DAGONL','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,3,9,1,NULL,'051022a',NULL,'25/06/2008',24948886,9,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,22368367,43,NULL,36,NULL,-9076,'DAGONL','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,3,13,1,NULL,'051022a',NULL,'25/06/2008',24948886,13,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-9076,'DAGONL','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,3,14,1,NULL,'051022a',NULL,'25/06/2008',24948886,14,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-9076,'DAGONL','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,1,22,1,NULL,'051022a',NULL,'25/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-9076,'DAGONL','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,3,53,1,NULL,'051022a',NULL,'25/06/2008',24948886,53,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,22368368,43,NULL,36,NULL,-9076,'DAGONL','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,10,62,1,NULL,'051022a',NULL,'25/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-9076,'DAGONL','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,3,76,1,NULL,'051022a',NULL,'25/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,'V',NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,22368369,43,NULL,36,'C',-9076,'DAGONL','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,12,157,1,NULL,'051022a',NULL,'25/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-9076,'DAGONL','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,14,202,1,NULL,'051022a',NULL,'25/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-9076,'DAGONL','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(4618518,351,12,209,1,NULL,'051022a',NULL,'25/06/2008',24948886,209,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'22/10/2005',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-9076,'DAGONL','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,355,1,NULL,'061209a',NULL,'19/06/2008',56162905,355,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'9/12/2006',NULL,NULL,NULL,NULL,42512001,43,NULL,21,NULL,-2914,'WEBCAS','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,246,1,NULL,'061209a',NULL,'19/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'V',NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,42513417,43,NULL,20,'C',-8291,'SYSADM','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,569,1,NULL,'070809a|080405d',NULL,'19/06/2008',NULL,569,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'9/08/2007',NULL,NULL,NULL,NULL,NULL,43,NULL,12,NULL,-2914,'APPINT','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,570,1,NULL,'070809a|080405d',NULL,'19/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'V',NULL,NULL,NULL,'9/08/2007',NULL,NULL,NULL,NULL,62964827,43,NULL,12,'C',-2914,'APPINT','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,571,1,NULL,'070809a|080405d',NULL,'19/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'V',NULL,NULL,NULL,'9/08/2007',NULL,NULL,NULL,NULL,62977429,43,NULL,12,'C',-2914,'APPINT','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,405,1,NULL,'080606a',NULL,'19/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,'V',NULL,NULL,NULL,'6/06/2008',NULL,NULL,NULL,NULL,80133610,43,NULL,1,'C',-6,'T3078218','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,320,1,NULL,'080311a',NULL,'19/06/2008',NULL,320,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'11/03/2008',NULL,NULL,NULL,NULL,NULL,43,NULL,5,NULL,-307,'APPINT','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,604,1,NULL,'080404a',NULL,'19/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,'V',NULL,NULL,NULL,'4/04/2008',NULL,NULL,NULL,NULL,77456648,43,NULL,4,'C',-226,'T3086703','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,500,1,NULL,'061227a',NULL,'19/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,'V',NULL,NULL,NULL,'27/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,19,NULL,-2914,'IVR','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,1,1,1,NULL,'061209a',NULL,'19/06/2008',56119830,1,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,21,NULL,-8291,'CLARIFY','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,1,2,1,NULL,'061209a',NULL,'19/06/2008',56119830,2,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,21,NULL,-8291,'CLARIFY','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,1,3,1,NULL,'071202a|080126d|080126a|080225d|080228a|080305d|080307a',NULL,'19/06/2008',105208142,3,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-3834,'T3077733','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,1,4,1,NULL,'071202a|080126d|080126a|080225d|080228a|080305d|080307a',NULL,'19/06/2008',105208142,4,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-3834,'T3077733','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,2,5,1,NULL,'071202a|080126d|080126a|080225d|080228a|080305d|080307a',NULL,'19/06/2008',105208142,5,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-3834,'T3077733','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,6,1,NULL,'061209a|061209d|061209a',NULL,'19/06/2008',56165181,6,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,23,NULL,-3834,'T3019276','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,7,1,NULL,'071202a|080126d|080126a|080225d|080228a|080305d|080307a',NULL,'19/06/2008',105208142,7,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-3834,'T3077733','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,8,1,NULL,'071202a|080126d|080126a|080225d|080228a|080305d|080307a',NULL,'19/06/2008',105208142,8,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-3834,'T3077733','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,9,1,NULL,'071202a|080126d|080126a|080225d|080228a|080305d|080307a',NULL,'19/06/2008',105208142,9,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,42064703,43,NULL,36,NULL,-3834,'T3077733','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,13,1,NULL,'071202a|080126d|080126a|080225d|080228a|080305d|080307a',NULL,'19/06/2008',105208142,13,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-3834,'T3077733','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,14,1,NULL,'071202a|080126d|080126a|080225d|080228a|080305d|080307a',NULL,'19/06/2008',105208142,14,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-3834,'T3077733','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,1,22,1,NULL,'061209a',NULL,'19/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,21,NULL,-8291,'CLARIFY','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,53,1,NULL,'071202a|080126d|080126a|080225d|080228a|080305d|080307a',NULL,'19/06/2008',105208142,53,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,42064705,43,NULL,36,NULL,-3834,'T3077733','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,10,62,1,NULL,'061209a|080307d',NULL,'19/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,21,NULL,-8291,'CLARIFY','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,76,1,NULL,'061209a',NULL,'19/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,'V',NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,42064707,43,NULL,22,'C',-8291,'CLARIFY','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,12,157,1,NULL,'071202a|080126d|080126a|080225d|080228a|080305d|080307a',NULL,'19/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,27,NULL,-3834,'T3077733','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,14,202,1,NULL,'071202a|080126d|080126a|080225d|080228a|080305d|080307a',NULL,'19/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,27,NULL,-3834,'T3077733','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,204,1,NULL,'061209a|061209d|061209a',NULL,'19/06/2008',56165181,204,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,23,NULL,-3834,'T3019276','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,12,209,1,NULL,'071202a|080126d|080126a|080225d|080228a|080305d|080307a',NULL,'19/06/2008',105208142,209,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,35,NULL,-3834,'T3077733','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,496,1,NULL,'061209a|080606d',NULL,'19/06/2008',115392777,496,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,'V',NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,42064709,43,NULL,23,'C',-8291,'CLARIFY','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,5,499,1,NULL,'061209a|080606d',NULL,'19/06/2008',115392842,499,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,'V',NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,22,NULL,-8291,'CLARIFY','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,517,1,NULL,'061209a|080606d',NULL,'19/06/2008',NULL,NULL,NULL,0,NULL,NULL,NULL,0,NULL,NULL,0,NULL,'V',NULL,NULL,NULL,'4/12/2006',NULL,NULL,NULL,NULL,NULL,43,NULL,21,NULL,-8291,'CLARIFY','C',NULL,NULL,NULL,NULL)
/
INSERT INTO CONTR_SERVICES
(CO_ID,TMCODE,SPCODE,SNCODE,CS_SEQNO,CS_CHANNEL_NUM,CS_STAT_CHNG,CS_ON_CBB,CS_DATE_BILLED,CS_REQUEST,SN_CLASS,CS_OVW_SUBSCR,CS_SUBSCRIPT,CS_OVW_ACCESS,CS_OVW_ACC_PRD,CS_OVW_ACC_FIRST,CS_ACCESS,CS_PENDING_STATE,CS_CHANNEL_EXCL,CS_DIS_SUBSCR,CS_ADV_CHARGE,CS_SRV_TYPE,SUBPAYER,USGPAYER,ACCPAYER,CS_ENTDATE,CS_OVW_LAST,INSTALL_DATE,TRIAL_END_DATE,CS_ADV_CHARGE_END_DATE,PRM_VALUE_ID,CURRENCY,CS_ADV_CHARGE_CURRENCY,REC_VERSION,SRV_SUBTYPE,DEALER_ID,USERNAME,INITIATOR_TYPE,BACKUP_CS_OVW_ACCESS,BACKUP_CS_OVW_ACC_PRD,BACKUP_CS_OVW_ACC_FIRST,BACKUP_CS_ACCESS)
VALUES
(7829813,354,3,75,1,NULL,'071201a|071202d|080126a|080126d|080225a|080228d|080305a|080307d',NULL,'19/06/2008',105215941,75,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'29 /11/ 2007',NULL,NULL,NULL,NULL,NULL,43,NULL,21,NULL,NULL,NULL,'C',NULL,NULL,NULL,NULL)
/


-- ACCOUNT7.OK and ACCOUNT7
INSERT INTO CONTR_SERVICES (CO_ID,SPCODE,SNCODE,TMCODE,CS_STAT_CHNG,CS_DATE_BILLED,CS_SEQNO, CURRENCY, REC_VERSION, INITIATOR_TYPE)
VALUES (5116309, 3, 604, 362, '081226a', NULL, 1, 43, 21, 'C')
/




/* updates */

update contr_services set CS_DATE_BILLED=null where co_id='4618517';
update contr_services set CS_DATE_BILLED=null where co_id='4618518';
update contr_services set CS_DATE_BILLED=null where co_id='7829813';
update contr_services set CS_STAT_CHNG='060627a' where co_id='4618517' and tmcode = 303 and spcode = 3 and sncode = 604;
update contr_services set sncode = 77 where co_id='4618518' and sncode = 76;
update contr_services set CS_STAT_CHNG='060626a' where co_id='4618518' and sncode = 77;
update contr_services set CS_STAT_CHNG='060626a' where co_id='7829813' and sncode = 76;
update mpulkpvb set subscript=15.0 where PV_COMBI_ID=3981 and set_id=1 and vscode=5;
update mpulktmb set subscript=12.5 where tmcode=351 and spcode=3 and sncode=76 and vscode=7;

